name: aliyun_oss_flutter
description: aliyun oss plugin for flutter. Use this plugin to upload files to aliyun oss.
version: 1.1.1
homepage: https://github.com/lucky1213/aliyun_oss

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.2

  http_parser: ^4.0.2

  crypto: ^3.0.2

  intl: ^0.19.0

  # A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^5.1.1

  uuid: ^4.5.1

dev_dependencies:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
